export const LOCALITY_BANNER_REQUEST = "LOCALITY_BANNER_REQUEST"
export const LOCALITY_BANNER_SUCCESS = "LOCALITY_BANNER_SUCCESS"
export const LOCALITY_BANNER_FAIL = "LOCALITY_BANNER_FAIL"

export const ALL_CAT_REQUEST = "ALL_CAT_REQUEST";
export const ALL_CAT_SUCCESS = "ALL_CAT_SUCCESS";
export const ALL_CAT_FAIL  = "ALL_CAT_FAIL";

export const DAY_OFFER_REQUEST = "DAY_OFFER_REQUEST";
export const DAY_OFFER_SUCCESS = "DAY_OFFER_SUCCESS";
export const DAY_OFFER_FAIL  = "DAY_OFFER_FAIL";

export const HOME_BRANDEDSTORE_REQUEST = "HOME_BRANDEDSTORE_REQUEST";
export const HOME_BRANDEDSTORE_SUCCESS = "HOME_BRANDEDSTORE_SUCCESS";
export const HOME_BRANDEDSTORE_FAIL  = "HOME_BRANDEDSTORE_FAIL";

export const BANNERS_REQUEST = "BANNERS_REQUEST";
export const BANNERS_SUCCESS = "BANNERS_SUCCESS";
export const BANNERS_FAIL  = "BANNERS_FAIL";

export const WEDDINGS_REQUEST = "WEDDINGS_REQUEST";
export const WEDDINGS_SUCCESS = "WEDDINGS_SUCCESS";
export const WEDDINGS_FAIL  = "WEDDINGS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR"