export const ALL_OFFER_REQUEST = "ALL_STORE_REQUEST";
export const ALL_OFFER_SUCCESS = "ALL_STORE_SUCCESS";
export const ALL_OFFER_FAIL  = "ALL_STORE_FAIL";



export const LISTING_CAT_REQUEST = "LISTING_CAT_REQUEST";
export const LISTING_CAT_SUCCESS = "LISTING_CAT_SUCCESS";
export const LISTING_CAT_FAIL  = "LISTING_CAT_FAIL";


export const LISTING_SUBCAT_REQUEST = "LISTING_SUBCAT_REQUEST";
export const LISTING_SUBCAT_SUCCESS = "LISTING_SUBCAT_SUCCESS";
export const LISTING_SUBCAT_FAIL  = "LISTING_SUBCAT_FAIL";

export const OFFER_DETAIL_REQUEST = "OFFER_DETAIL_REQUEST";
export const OFFER_DETAIL_SUCCESS = "OFFER_DETAIL_SUCCESS";
export const OFFER_DETAIL_FAIL  = "OFFER_DETAIL_FAIL";

export const SELECTED_OFFER_DETAIL = 'SELECTED_OFFER_DETAIL';

export const FESTIVE_OFFER_REQUEST = "FESTIVE_STORE_REQUEST";
export const FESTIVE_OFFER_SUCCESS = "FESTIVE_STORE_SUCCESS";
export const FESTIVE_OFFER_FAIL  = "FESTIVE_STORE_FAIL";

export const FIFTYOFF_OFFER_REQUEST = "FIFTYOFF_STORE_REQUEST";
export const FIFTYOFF_OFFER_SUCCESS = "FIFTYOFF_STORE_SUCCESS";
export const FIFTYOFF_OFFER_FAIL  = "FIFTYOFF_STORE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";