export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAIL = "OTP_FAIL";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";

export const OTPVERIFY_REQUEST = "OTPVERIFY_REQUEST";
export const OTPVERIFY_SUCCESS = "OTPVERIFY_SUCCESS";
export const OTPVERIFY_FAIL = "OTPVERIFY_FAIL";

export const USERDETAIL_CHANGE = "USERDETAIL_CHANGE";

export const REGISTRATION_DATA_CHANGE = "REGISTRATION_DATA_CHANGE";

export const UPLOAD_PROFILE_REQUEST = "UPLOAD_PROFILE_REQUEST";
export const UPLOAD_PROFILE_SUCCESS = "UPLOAD_PROFILE_SUCCESS";
export const UPLOAD_PROFILE_FAIL = "UPLOAD_PROFILE_FAIL";

export const UPDATE_USER_DATA_REQUEST = "UPDATE_USER_DATA_REQUEST";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAIL = "UPDATE_USER_DATA_FAIL";


export const GET_USER_REQUEST = "GET_USER_REQUEST_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const VERIFIED_USER = "VERIFIED_USER";
