export const VENDOR_REQUEST = 'VENDOR_REQUEST';
export const VENDOR_SUCCESS = 'VENDOR_SUCCESS';
export const VENDOR_FAIL = 'VENDOR_FAIL';

export const VENDOR_FILTER_REQUEST = 'VENDOR_FILTER_REQUEST';
export const VENDOR_FILTER_SUCCESS = 'VENDOR_FILTER_SUCCESS';
export const VENDOR_FILTER_FAIL = 'VENDOR_FILTER_FAIL';

export const VENDOR_DETAIL = 'VENDOR_DETAIL';

export const SELECTED_VENDOR_DETAIL = 'SELECTED_VENDOR_DETAIL';

export const VENDOR_LIKE = 'VENDOR_LIKE';
export const VENDOR_UNLIKE = 'VENDOR_UNLIKE';

export const VENDOR_REVIEW_REQUEST = 'VENDOR_REVIEW_REQUEST';
export const VENDOR_REVIEW_SUCCESS = 'VENDOR_REVIEW_SUCCESS';
export const VENDOR_REVIEW_FAIL = 'VENDOR_REVIEW_FAIL';

export const GET_VENDOR_REVIEW_REQUEST = 'GET_VENDOR_REVIEW_REQUEST';
export const GET_VENDOR_REVIEW_SUCCESS = 'GET_VENDOR_REVIEW_SUCCESS';
export const GET_VENDOR_REVIEW_FAIL = 'GET_VENDOR_REVIEW_FAIL';

export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const GET_SUB_CATEGORY_LIST_REQUEST = 'GET_SUB_CATEGORY_LIST_REQUEST';
export const GET_SUB_CATEGORY_LIST_SUCCESS = 'GET_SUB_CATEGORY_LIST_SUCCESS';
export const GET_SUB_CATEGORY_LIST_FAIL = 'GET_SUB_CATEGORY_LIST_FAIL';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const GET_FAVORITE_VENDOR_REQUEST = 'GET_FAVORITE_VENDOR_REQUEST';
export const GET_FAVORITE_VENDOR_SUCCESS = 'GET_FAVORITE_VENDOR_SUCCESS';
export const GET_FAVORITE_VENDOR_FAIL = 'GET_FAVORITE_VENDOR_FAIL';

